export default {
  carousel_img1: require('../assets/images/carousel_img1.png'),
  carousel_img2: require('../assets/images/carousel_img2.png'),
  carousel_img3: require('../assets/images/carousel_img3.png'),
  carousel_img4: require('../assets/images/carousel_img1.png'),
  slider_img1: require('../assets/images/img1.png'),
  slider_img2: require('../assets/images/img2.jpg'),
  slider_img3: require('../assets/images/img3.jpg'),
  slider_img4: require('../assets/images/img4.jpg'),
  slider_img5: require('../assets/images/img5.jpg'),
  slider_img6: require('../assets/images/img6.jpg'),
  logo: require('../assets/images/logo.png'),
  image_bg: require('../assets/images/image-bg.jpg'),
  dropdownTriangle: require('../assets/images/ic_dropdown.png'),
  fb: require('../assets/images/ic_facebook.png'),
  apple: require('../assets/images/ic_apple.png'),
  google: require('../assets/images/ic_google.png'),
  insta: require('../assets/images/ic_insta.png'),
  back: require('../assets/images/ic_back.png'),
  backWithSquare: require('../assets/images/backWithSquare.png'),
  rightBlue: require('../assets/images/ic_goA.png'),
};
