export default {
  Login: 'Login',
  SignUp: 'SignUp',
  LandingPage: 'LandingPage',
  AuthPage: 'AuthPage',
  NavDrawer: 'NavDrawer',
  TabRoutes: 'TabRoutes',
  HomeTab: 'HomeTab',
  ViewImage: 'ViewImage',
  ProfileTab: 'ProfileTab',
  Cart: 'Cart',
  OtpVerification: 'OtpVerification',
  Profiles: 'Profiles',
  SearchProfiles: 'SearchProfiles',
};
