export default {
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  LOGGED_IN: 'LOGGED_IN',
  LOG_OUT: 'LOG_OUT',
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_QUANTITY: 'ADD_QUANTITY',
  SUBTRACT_QUANTITY: 'SUBTRACT_QUANTITY',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  PLACE_ORDER: 'PLACE_ORDER',
  ADD_PROFILES: 'ADD_PROFILES',
  CHANGE_TO_RED: 'CHANGE_TO_RED',
  CHANGE_TO_BLUE: 'CHANGE_TO_BLUE',
};
